# Generated by Django 5.0.4 on 2024-04-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='college',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='Collage',
        ),
    ]
